import React from 'react'
import Image from 'next/image'
import Head from 'next/head'

const Layout = (props: {children: React.ReactChild}) => {
  return (
    <div className="py-8">
        <header>
        <Head>
          <title>Pagination</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        </header>
        {props.children}
        <footer className="flex flex-1 px-8 border-t border-solid border-grey justify-center items-center">
          <span className="mt-4">
            Powered by{' '}
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </footer>
    </div>
  )
}

export default Layout